server:
  port: 12374
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/myhub?serverTimeZone=UTC
  freemarker:
    cache: false
  thymeleaf:
    cache: false
  flyway:
    enabled: true

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.diao.myhub.model
  configuration:
    map-underscore-to-camel-case: true

springfox:
  documentation:
    enabled: true
    swagger-ui:
      enabled: true
    open-api:
      enabled: true
logging:
  file:
    name: log/myhub.log
  level:
    root: info
    life:
      com.diao.myhub.mapper: debug
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 30

gitee:
  client:
    grant_type: authorization_code
    client_id: 721e8b39b94d2671338006a93a9d578dca226c37d5e9f8a90d12b9ba8e2b2b3f
    client_secret: 9ce4f762b693e4aa00ed236e8f829b1ad6ff6925266275fd420d046e8646b9e1
    redirect_uri: http://192.168.5.17:12374/callback
    getOAuth_url: https://gitee.com/oauth/authorize?client_id=721e8b39b94d2671338006a93a9d578dca226c37d5e9f8a90d12b9ba8e2b2b3f&&redirect_uri=http://192.168.5.17:12374/callback&&response_type=code
cosClient:
  secretId: "AKIDIPGqADzTgcHflbAm7ByUjgNmulLegQt5"
  secretKey: "wbz7xXprc5HH0RbT6SWJq65mEPJvGJ5Z"
