package com.diao.myhub.model;

import lombok.Data;

@Data
public class Notify {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notify.id
     *
     * @mbg.generated Wed Aug 25 20:11:48 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notify.notifier
     *
     * @mbg.generated Wed Aug 25 20:11:48 CST 2021
     */
    private Integer notifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notify.receiver
     *
     * @mbg.generated Wed Aug 25 20:11:48 CST 2021
     */
    private Integer receiver;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notify.outer_id
     *
     * @mbg.generated Wed Aug 25 20:11:48 CST 2021
     */
    private Long outerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notify.type
     *
     * @mbg.generated Wed Aug 25 20:11:48 CST 2021
     */
    private Short type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notify.gmt_create
     *
     * @mbg.generated Wed Aug 25 20:11:48 CST 2021
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notify.status
     *
     * @mbg.generated Wed Aug 25 20:11:48 CST 2021
     */
    private Short status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notify.outer_title
     *
     * @mbg.generated Wed Aug 25 20:11:48 CST 2021
     */
    private String outerTitle;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify.id
     *
     * @return the value of notify.id
     *
     * @mbg.generated Wed Aug 25 20:11:48 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify.id
     *
     * @param id the value for notify.id
     *
     * @mbg.generated Wed Aug 25 20:11:48 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify.notifier
     *
     * @return the value of notify.notifier
     *
     * @mbg.generated Wed Aug 25 20:11:48 CST 2021
     */
    public Integer getNotifier() {
        return notifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify.notifier
     *
     * @param notifier the value for notify.notifier
     *
     * @mbg.generated Wed Aug 25 20:11:48 CST 2021
     */
    public void setNotifier(Integer notifier) {
        this.notifier = notifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify.receiver
     *
     * @return the value of notify.receiver
     *
     * @mbg.generated Wed Aug 25 20:11:48 CST 2021
     */
    public Integer getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify.receiver
     *
     * @param receiver the value for notify.receiver
     *
     * @mbg.generated Wed Aug 25 20:11:48 CST 2021
     */
    public void setReceiver(Integer receiver) {
        this.receiver = receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify.outer_id
     *
     * @return the value of notify.outer_id
     *
     * @mbg.generated Wed Aug 25 20:11:48 CST 2021
     */
    public Long getOuterId() {
        return outerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify.outer_id
     *
     * @param outerId the value for notify.outer_id
     *
     * @mbg.generated Wed Aug 25 20:11:48 CST 2021
     */
    public void setOuterId(Long outerId) {
        this.outerId = outerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify.type
     *
     * @return the value of notify.type
     *
     * @mbg.generated Wed Aug 25 20:11:48 CST 2021
     */
    public Short getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify.type
     *
     * @param type the value for notify.type
     *
     * @mbg.generated Wed Aug 25 20:11:48 CST 2021
     */
    public void setType(Short type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify.gmt_create
     *
     * @return the value of notify.gmt_create
     *
     * @mbg.generated Wed Aug 25 20:11:48 CST 2021
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify.gmt_create
     *
     * @param gmtCreate the value for notify.gmt_create
     *
     * @mbg.generated Wed Aug 25 20:11:48 CST 2021
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify.status
     *
     * @return the value of notify.status
     *
     * @mbg.generated Wed Aug 25 20:11:48 CST 2021
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify.status
     *
     * @param status the value for notify.status
     *
     * @mbg.generated Wed Aug 25 20:11:48 CST 2021
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify.outer_title
     *
     * @return the value of notify.outer_title
     *
     * @mbg.generated Wed Aug 25 20:11:48 CST 2021
     */
    public String getOuterTitle() {
        return outerTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify.outer_title
     *
     * @param outerTitle the value for notify.outer_title
     *
     * @mbg.generated Wed Aug 25 20:11:48 CST 2021
     */
    public void setOuterTitle(String outerTitle) {
        this.outerTitle = outerTitle == null ? null : outerTitle.trim();
    }
}
