package com.diao.myhub.mapper;

import com.diao.myhub.model.Comment;
import com.diao.myhub.model.CommentExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

@Mapper
public interface CommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Mon Aug 23 00:04:55 CST 2021
     */
    long countByExample(CommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Mon Aug 23 00:04:55 CST 2021
     */
    int deleteByExample(CommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Mon Aug 23 00:04:55 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Mon Aug 23 00:04:55 CST 2021
     */
    int insert(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Mon Aug 23 00:04:55 CST 2021
     */
    int insertSelective(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Mon Aug 23 00:04:55 CST 2021
     */
    List<Comment> selectByExample(CommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Mon Aug 23 00:04:55 CST 2021
     */
    Comment selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Mon Aug 23 00:04:55 CST 2021
     */
    int updateByExampleSelective(@Param("record") Comment record, @Param("example") CommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Mon Aug 23 00:04:55 CST 2021
     */
    int updateByExample(@Param("record") Comment record, @Param("example") CommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Mon Aug 23 00:04:55 CST 2021
     */
    int updateByPrimaryKeySelective(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Mon Aug 23 00:04:55 CST 2021
     */
    int updateByPrimaryKey(Comment record);
    /**
     * 自定义映射器
     */
    @Select("select count(1) from myhub.comment where parent_id = #{id} and type=1 ")
    int getCommentCount(Long pid);
    @Select("select count(1) from myhub.comment where parent_id = #{id} and type=2")
    Long getSubCommentCount(Long pid);
    @Select("select * from myhub.comment where id=#{id}")
    Comment getCommentById(Long id);
    @Update("update myhub.comment set like_count = like_count + 1 where id = #{likeId}")
    int updateLikeInc(Long likeId);
    @Update("update myhub.comment set like_count = like_count - 1 where id = #{likeId}")
    int updateLikeDec(Long likeId);
}
