package com.diao.myhub.mapper;

import com.diao.myhub.model.Great;
import com.diao.myhub.model.GreatExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface GreatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table great
     *
     * @mbg.generated Sun Aug 29 00:53:16 CST 2021
     */
    long countByExample(GreatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table great
     *
     * @mbg.generated Sun Aug 29 00:53:16 CST 2021
     */
    int deleteByExample(GreatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table great
     *
     * @mbg.generated Sun Aug 29 00:53:16 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table great
     *
     * @mbg.generated Sun Aug 29 00:53:16 CST 2021
     */
    int insert(Great record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table great
     *
     * @mbg.generated Sun Aug 29 00:53:16 CST 2021
     */
    int insertSelective(Great record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table great
     *
     * @mbg.generated Sun Aug 29 00:53:16 CST 2021
     */
    List<Great> selectByExample(GreatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table great
     *
     * @mbg.generated Sun Aug 29 00:53:16 CST 2021
     */
    Great selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table great
     *
     * @mbg.generated Sun Aug 29 00:53:16 CST 2021
     */
    int updateByExampleSelective(@Param("record") Great record, @Param("example") GreatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table great
     *
     * @mbg.generated Sun Aug 29 00:53:16 CST 2021
     */
    int updateByExample(@Param("record") Great record, @Param("example") GreatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table great
     *
     * @mbg.generated Sun Aug 29 00:53:16 CST 2021
     */
    int updateByPrimaryKeySelective(Great record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table great
     *
     * @mbg.generated Sun Aug 29 00:53:16 CST 2021
     */
    int updateByPrimaryKey(Great record);
}
