package com.diao.myhub.mapper;

import com.diao.myhub.model.Notify;
import com.diao.myhub.model.NotifyExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Update;

@Mapper
public interface NotifyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notify
     *
     * @mbg.generated Wed Aug 25 20:11:48 CST 2021
     */
    long countByExample(NotifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notify
     *
     * @mbg.generated Wed Aug 25 20:11:48 CST 2021
     */
    int deleteByExample(NotifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notify
     *
     * @mbg.generated Wed Aug 25 20:11:48 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notify
     *
     * @mbg.generated Wed Aug 25 20:11:48 CST 2021
     */
    int insert(Notify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notify
     *
     * @mbg.generated Wed Aug 25 20:11:48 CST 2021
     */
    int insertSelective(Notify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notify
     *
     * @mbg.generated Wed Aug 25 20:11:48 CST 2021
     */
    List<Notify> selectByExample(NotifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notify
     *
     * @mbg.generated Wed Aug 25 20:11:48 CST 2021
     */
    Notify selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notify
     *
     * @mbg.generated Wed Aug 25 20:11:48 CST 2021
     */
    int updateByExampleSelective(@Param("record") Notify record, @Param("example") NotifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notify
     *
     * @mbg.generated Wed Aug 25 20:11:48 CST 2021
     */
    int updateByExample(@Param("record") Notify record, @Param("example") NotifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notify
     *
     * @mbg.generated Wed Aug 25 20:11:48 CST 2021
     */
    int updateByPrimaryKeySelective(Notify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notify
     *
     * @mbg.generated Wed Aug 25 20:11:48 CST 2021
     */
    int updateByPrimaryKey(Notify record);
    @Update("update myhub.notify set status=#{status} where receiver=#{uid} and status=0")
    int readMsg(int uid,short status);
    @Update("update myhub.notify set status=#{status} where id=#{id}")
    int readOneMsg(Long id,short status);
}
